"""empty message

Revision ID: 08dc170e61cc
Revises: 446c2bd5db60
Create Date: 2022-03-09 16:14:55.657600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dc170e61cc'
down_revision = '446c2bd5db60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_thesis_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_diploma_themes_supervisor_thesis_id_users'), 'users', ['supervisor_thesis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('diploma_themes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_diploma_themes_supervisor_thesis_id_users'), type_='foreignkey')
        batch_op.drop_column('supervisor_thesis_id')

    # ### end Alembic commands ###
