"""empty message

Revision ID: 169101fef7d5
Revises: a05df4a2a54f
Create Date: 2022-10-18 21:46:57.781740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169101fef7d5'
down_revision = 'a05df4a2a54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('thesis_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('comment_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_report', schema=None) as batch_op:
        batch_op.drop_column('comment_time')
        batch_op.drop_column('comment')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_deadline_worktype_id_worktype'), type_='foreignkey')
        batch_op.drop_column('worktype_id')

    with op.batch_alter_table('current_thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.INTEGER(), nullable=True))

    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    # ### end Alembic commands ###
