"""empty message

Revision ID: 1925f5327423
Revises: c05d8ad16025
Create Date: 2022-11-26 13:27:08.604498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1925f5327423'
down_revision = 'c05d8ad16025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('thesis_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_report', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.alter_column('worktype_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('current_thesis', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('presentation_link')
        batch_op.drop_column('text_link')
        batch_op.drop_column('text_uri')
        batch_op.drop_column('goal')

    op.create_table('notification_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=512), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('viewed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='fk_notification_account_recipient_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_notification_account')
    )
    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    op.drop_table('thesis_task')
    op.drop_table('notification_coursework')
    # ### end Alembic commands ###
