"""empty message

Revision ID: 2376c1f1f414
Revises: a6628a140731
Create Date: 2021-07-12 17:29:40.336034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2376c1f1f414'
down_revision = 'a6628a140731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summer_school', sa.Column('project_name', sa.String(length=1024), nullable=True))
    op.add_column('summer_school', sa.Column('description', sa.String(length=2048), nullable=True))
    op.add_column('summer_school', sa.Column('tech', sa.String(length=1024), nullable=True))
    op.add_column('summer_school', sa.Column('repo', sa.String(length=1024), nullable=True))
    op.add_column('summer_school', sa.Column('demos', sa.String(length=1024), nullable=True))
    op.add_column('summer_school', sa.Column('advisors', sa.String(length=1024), nullable=True))
    op.add_column('summer_school', sa.Column('requirements', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summer_school', 'requirements')
    op.drop_column('summer_school', 'advisors')
    op.drop_column('summer_school', 'demos')
    op.drop_column('summer_school', 'repo')
    op.drop_column('summer_school', 'tech')
    op.drop_column('summer_school', 'description')
    op.drop_column('summer_school', 'project_name')
    # ### end Alembic commands ###
