"""empty message

Revision ID: 25130df4ed9f
Revises: 
Create Date: 2022-01-20 15:48:13.864008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25130df4ed9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), server_default=sa.schema.DefaultClause("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('summer_school', 'requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('summer_school', 'project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###
