"""empty message

Revision ID: 50699d0a61d4
Revises: 1fe48662062e
Create Date: 2023-09-28 12:39:44.551742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50699d0a61d4'
down_revision = '1fe48662062e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grants')
    op.drop_table('_alembic_tmp_deadline')
    op.drop_table('notification_coursework')
    with op.batch_alter_table('current_thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultant', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('code_link', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.alter_column('worktype_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_staff_official_email'), ['official_email'])

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.alter_column('worktype_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('current_thesis', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('account_name')
        batch_op.drop_column('code_link')
        batch_op.drop_column('consultant')

    op.create_table('notification_coursework',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=512), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('viewed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='fk_notification_coursework_recipient_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_notification_coursework')
    )
    op.create_table('_alembic_tmp_deadline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_id', sa.INTEGER(), nullable=False),
    sa.Column('choose_topic', sa.DATETIME(), nullable=True),
    sa.Column('submit_work_for_review', sa.DATETIME(), nullable=True),
    sa.Column('upload_reviews', sa.DATETIME(), nullable=True),
    sa.Column('pre_defense', sa.DATETIME(), nullable=True),
    sa.Column('defense', sa.DATETIME(), nullable=True),
    sa.Column('worktype_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_study.id'], name='fk_deadline_area_id_areas_of_study'),
    sa.ForeignKeyConstraint(['worktype_id'], ['worktype.id'], name='fk_deadline_worktype_id_worktype'),
    sa.PrimaryKeyConstraint('id', name='pk_deadline')
    )
    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    # ### end Alembic commands ###
