"""empty message

Revision ID: 538ea31d3311
Revises: 25130df4ed9f
Create Date: 2022-02-04 08:52:12.130525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538ea31d3311'
down_revision = '25130df4ed9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('logo_uri', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diploma_themes_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diploma_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2048), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('consultant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['themes_level.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diploma_themes_tag',
    sa.Column('diploma_themes_tag_id', sa.Integer(), nullable=False),
    sa.Column('diploma_themes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diploma_themes_id'], ['diploma_themes.id'], ),
    sa.ForeignKeyConstraint(['diploma_themes_tag_id'], ['diploma_themes_tags.id'], ),
    sa.PrimaryKeyConstraint('diploma_themes_tag_id', 'diploma_themes_id')
    )
    op.drop_table('grants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summer_school', 'requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('summer_school', 'description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('summer_school', 'project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('post_vote', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diploma_themes_tag')
    op.drop_table('diploma_themes')
    op.drop_table('themes_level')
    op.drop_table('diploma_themes_tags')
    op.drop_table('company')
    # ### end Alembic commands ###
