"""empty message

Revision ID: 54fd2c6e5760
Revises: 84ec21521d43
Create Date: 2022-05-02 10:36:18.775422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fd2c6e5760'
down_revision = '84ec21521d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_thesis_area_id_areas_of_study'), 'areas_of_study', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_area_id_areas_of_study'), type_='foreignkey')
        batch_op.drop_column('area_id')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
