"""empty message

Revision ID: 84ec21521d43
Revises: 08dc170e61cc
Create Date: 2022-04-26 11:16:58.627399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ec21521d43'
down_revision = '08dc170e61cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_of_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas_of_study'))
    )
    op.create_table('thesis_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('o1', sa.Integer(), nullable=True),
    sa.Column('o1_comment', sa.String(length=1024), nullable=True),
    sa.Column('o2', sa.Integer(), nullable=True),
    sa.Column('o2_comment', sa.String(length=1024), nullable=True),
    sa.Column('t1', sa.Integer(), nullable=True),
    sa.Column('t1_comment', sa.String(length=1024), nullable=True),
    sa.Column('t2', sa.Integer(), nullable=True),
    sa.Column('t2_comment', sa.String(length=1024), nullable=True),
    sa.Column('p1', sa.Integer(), nullable=True),
    sa.Column('p1_comment', sa.String(length=1024), nullable=True),
    sa.Column('p2', sa.Integer(), nullable=True),
    sa.Column('p2_comment', sa.String(length=1024), nullable=True),
    sa.Column('verdict', sa.Integer(), nullable=False),
    sa.Column('overall_comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], name=op.f('fk_thesis_review_thesis_id_thesis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_review'))
    )

    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_thesis_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_author_id_users'), type_='foreignkey')
        batch_op.drop_column('review_status')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('thesis_review')
    op.drop_table('areas_of_study')
    # ### end Alembic commands ###
