"""empty message

Revision ID: 925985497ccc
Revises: 726436b16db5
Create Date: 2022-05-04 20:22:07.293786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925985497ccc'
down_revision = '726436b16db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_on_review_worktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_on_review_worktype'))
    )

    with op.batch_alter_table('thesis_on_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_on_review_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_thesis_on_review_thesis_on_review_type_id_thesis_on_review_worktype'), 'thesis_on_review_worktype', ['thesis_on_review_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_on_review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_on_review_thesis_on_review_type_id_thesis_on_review_worktype'), type_='foreignkey')
        batch_op.drop_column('thesis_on_review_type_id')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('thesis_on_review_worktype')
    # ### end Alembic commands ###
