"""empty message

Revision ID: a05df4a2a54f
Revises: e24cafdefc27
Create Date: 2022-10-13 18:08:57.861152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05df4a2a54f'
down_revision = 'e24cafdefc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internship_tag'))
    )
    op.create_table('internships_tag',
    sa.Column('internships_tag_id', sa.Integer(), nullable=False),
    sa.Column('internships_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internships_id'], ['internships.id'], name=op.f('fk_internships_tag_internships_id_internships')),
    sa.ForeignKeyConstraint(['internships_tag_id'], ['internship_tag.id'], name=op.f('fk_internships_tag_internships_tag_id_internship_tag')),
    sa.PrimaryKeyConstraint('internships_tag_id', 'internships_id', name=op.f('pk_internships_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    op.drop_table('internships_tag')
    op.drop_table('internship_tag')
    # ### end Alembic commands ###
