"""empty message

Revision ID: c250ebb1be35
Revises: 54fd2c6e5760
Create Date: 2022-05-03 22:06:38.549935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250ebb1be35'
down_revision = '54fd2c6e5760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_reviewer_company_id_company')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviewer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer'))
    )
    op.create_table('thesis_on_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('name_ru', sa.String(length=512), nullable=False),
    sa.Column('text_uri', sa.String(length=512), nullable=True),
    sa.Column('presentation_uri', sa.String(length=512), nullable=True),
    sa.Column('source_uri', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_study.id'], name=op.f('fk_thesis_on_review_area_id_areas_of_study')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_thesis_on_review_author_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewer.id'], name=op.f('fk_thesis_on_review_reviewer_id_reviewer')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['staff.id'], name=op.f('fk_thesis_on_review_supervisor_id_staff')),
    sa.ForeignKeyConstraint(['type_id'], ['worktype.id'], name=op.f('fk_thesis_on_review_type_id_worktype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_on_review'))
    )


    with op.batch_alter_table('thesis_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesis_on_review_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_thesis_review_thesis_on_review_id_thesis_on_review'), 'thesis_on_review', ['thesis_on_review_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_review_thesis_on_review_id_thesis_on_review'), type_='foreignkey')
        batch_op.drop_column('thesis_on_review_id')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('thesis_on_review')
    op.drop_table('reviewer')
    # ### end Alembic commands ###
