"""empty message

Revision ID: c44ed75ba53d
Revises: 06bbb2e38dc7
Create Date: 2022-06-05 22:23:19.436738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44ed75ba53d'
down_revision = '06bbb2e38dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('logo_uri', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internship_company'))
    )
    op.create_table('internship_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internship_format'))
    )
    op.create_table('internships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_vacancy', sa.String(length=70), nullable=False),
    sa.Column('salary', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('more_inf', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_internships_author_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['internship_company.id'], name=op.f('fk_internships_company_id_internship_company')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internships'))
    )
    op.create_table('internships_format',
    sa.Column('internships_format_id', sa.Integer(), nullable=False),
    sa.Column('internships_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internships_format_id'], ['internship_format.id'], name=op.f('fk_internships_format_internships_format_id_internship_format')),
    sa.ForeignKeyConstraint(['internships_id'], ['internships.id'], name=op.f('fk_internships_format_internships_id_internships')),
    sa.PrimaryKeyConstraint('internships_format_id', 'internships_id', name=op.f('pk_internships_format'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('internships_format')
    op.drop_table('internships')
    op.drop_table('internship_format')
    op.drop_table('internship_company')
    # ### end Alembic commands ###
