"""empty message

Revision ID: c48f0da3462c
Revises: 1925f5327423
Create Date: 2022-12-15 09:50:45.422041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48f0da3462c'
down_revision = '1925f5327423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_on_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_on_review', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.alter_column('worktype_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_deadline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_id', sa.INTEGER(), nullable=False),
    sa.Column('choose_topic', sa.DATETIME(), nullable=True),
    sa.Column('submit_work_for_review', sa.DATETIME(), nullable=True),
    sa.Column('upload_reviews', sa.DATETIME(), nullable=True),
    sa.Column('pre_defense', sa.DATETIME(), nullable=True),
    sa.Column('defense', sa.DATETIME(), nullable=True),
    sa.Column('worktype_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_study.id'], name='fk_deadline_area_id_areas_of_study'),
    sa.ForeignKeyConstraint(['worktype_id'], ['worktype.id'], name='fk_deadline_worktype_id_worktype'),
    sa.PrimaryKeyConstraint('id', name='pk_deadline')
    )
    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    # ### end Alembic commands ###
