"""empty message

Revision ID: cf8a829be2e0
Revises: 1d36e5ec34c6
Create Date: 2022-02-10 17:53:52.829147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8a829be2e0'
down_revision = '1d36e5ec34c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('diploma_themes_level',
    #sa.Column('themes_level_id', sa.Integer(), nullable=False),
    #sa.Column('diploma_themes_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['diploma_themes_id'], ['diploma_themes.id'], name=op.f('fk_diploma_themes_level_diploma_themes_id_diploma_themes')),
    #sa.ForeignKeyConstraint(['themes_level_id'], ['themes_level.id'], name=op.f('fk_diploma_themes_level_themes_level_id_themes_level')),
    #sa.PrimaryKeyConstraint('themes_level_id', 'diploma_themes_id', name=op.f('pk_diploma_themes_level'))
    #)
    with op.batch_alter_table('diploma_themes', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level_id')

    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('how_to_contact', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('how_to_contact')

    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('diploma_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'themes_level', ['level_id'], ['id'])

    op.drop_table('diploma_themes_level')
    # ### end Alembic commands ###
