"""empty message

Revision ID: e24cafdefc27
Revises: 33ca5df0bfc2
Create Date: 2022-10-11 14:24:08.178581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24cafdefc27'
down_revision = '33ca5df0bfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('choose_topic', sa.DateTime(), nullable=True),
    sa.Column('submit_work_for_review', sa.DateTime(), nullable=True),
    sa.Column('upload_reviews', sa.DateTime(), nullable=True),
    sa.Column('pre_defense', sa.DateTime(), nullable=True),
    sa.Column('defense', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_study.id'], name=op.f('fk_deadline_area_id_areas_of_study')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deadline'))
    )
    op.create_table('notification_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notification_account_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_account'))
    )
    op.create_table('current_thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('worktype_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_review_uri', sa.String(length=512), nullable=True),
    sa.Column('reviewer_review_uri', sa.String(length=512), nullable=True),
    sa.Column('presentation_uri', sa.String(length=512), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas_of_study.id'], name=op.f('fk_current_thesis_area_id_areas_of_study')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_current_thesis_author_id_users')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['staff.id'], name=op.f('fk_current_thesis_supervisor_id_staff')),
    sa.ForeignKeyConstraint(['worktype_id'], ['worktype.id'], name=op.f('fk_current_thesis_worktype_id_worktype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_thesis'))
    )
    op.create_table('thesis_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('current_thesis_id', sa.Integer(), nullable=True),
    sa.Column('was_done', sa.String(length=2048), nullable=True),
    sa.Column('planned_to_do', sa.String(length=2048), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_thesis_report_author_id_users')),
    sa.ForeignKeyConstraint(['current_thesis_id'], ['current_thesis.id'], name=op.f('fk_thesis_report_current_thesis_id_current_thesis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_report'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summer_school', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('advisors',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('tech',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staff_official_email'), type_='unique')

    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('submission', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_grants')
    )
    op.drop_table('thesis_report')
    op.drop_table('current_thesis')
    op.drop_table('notification_account')
    op.drop_table('deadline')
    # ### end Alembic commands ###
