"""Add google auth + hackernews

Revision ID: fcd4d79a0c62
Revises: 2376c1f1f414
Create Date: 2022-01-19 16:26:07.537047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd4d79a0c62'
down_revision = '2376c1f1f414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('uri', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('text', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('votes', sa.INTEGER(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('rank', sa.FLOAT(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
