# -*- coding: utf-8 -*-
"""Guardrail for the asset build pipeline (perf/build-pipeline).

The production css/js are regenerated by `npm run build` from the committed
sources (purgecss + terser/esbuild) and committed. These tests protect the
deployable contract:

- the 4 bases + admin master reference the MINIFIED files, never the 595 KB
  unminified theme (and never the stale 60 KB / 701-rule build);
- the committed min css is not a stale/truncated build (rule-count floor);
- every class a template uses literally survives the purge, mirroring
  purgecss's own semantics (a selector is kept iff ALL its classes are used);
- every `asset()`/`url_for('static')` reference in the bases resolves to a real
  file (a broken build removing a referenced asset fails here, not on prod).

The authoritative drift check is the CI `assets` job (npm run build + git diff
--exit-code); these tests give fast local feedback without node.
"""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = REPO_ROOT / "src" / "templates"
STATIC_DIR = REPO_ROOT / "src" / "static"
CSS_SOURCE = STATIC_DIR / "assets" / "css" / "quick-website.css"
CSS_MIN = STATIC_DIR / "assets" / "css" / "quick-website.min.css"
JS_MIN = STATIC_DIR / "assets" / "js" / "quick-website.min.js"

BASES = [
    "base_dark.html",
    "base_dark_footer_white.html",
    "base_light.html",
    "base_light_footer_white.html",
    "admin/master.html",
]

MIN_RULE_FLOOR = 1200

# Mirrors `dynamicPrefixes` in scripts/build-assets.mjs: class families built
# dynamically in JS (string concatenation) that a static scan cannot see.
DYNAMIC_PREFIXES = [
    "popover-",
    "swiper-",
    "select2-",
    "flatpickr-",
    "fc-",
    "hljs-",
    "countdown-",
    "scroll-",
    "ps-",
    "tagsinput-",
    "label-",
    "toast-",
    "tooltip-",
    "g-sidenav-",
    "sidenav-",
    "omnisearch-",
]


def _rule_count(css: str) -> int:
    return len(re.findall(r"\{", css))


def _class_tokens(text: str) -> set[str]:
    return set(re.findall(r"[A-Za-z0-9_-]+", text))


def _skip_quote(s: str, i: int) -> int:
    q = s[i]
    i += 1
    n = len(s)
    while i < n:
        if s[i] == "\\":
            i += 2
            continue
        if s[i] == q:
            return i + 1
        i += 1
    return n


def _matching_brace(s: str, i: int) -> int:
    depth = 0
    n = len(s)
    while i < n:
        if s[i] in "\"'":
            i = _skip_quote(s, i)
            continue
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return n


def _leaf_rules(css: str) -> list[tuple[str, str]]:
    """Return (selector, declaration-block) leaf rules.

    `@media`/`@supports`/`@keyframes` groups are unwrapped: their inner rules
    become leaves whose selector is prefixed by the at-rule text, so the
    class-companion analysis sees the full selector context. Strings and
    comments are skipped so braces inside `url(data:...)` don't confuse
    the top-level brace matching.
    """

    def scan(s: str, prefix: str, out: list[tuple[str, str]]) -> None:
        i, n = 0, len(s)
        seg_start = 0
        while i < n:
            if s.startswith("/*", i):
                end = s.find("*/", i + 2)
                i = n if end == -1 else end + 2
                continue
            ch = s[i]
            if ch in "\"'":
                i = _skip_quote(s, i)
                continue
            if ch == "{":
                close = _matching_brace(s, i)
                selector = re.sub(r"\s+", " ", s[seg_start:i]).strip()
                inner = s[i + 1 : close]
                if selector.startswith("@"):
                    scan(inner, (prefix + " " + selector).strip(), out)
                else:
                    out.append(((prefix + " " + selector).strip(), inner))
                i = close + 1
                seg_start = i
            elif ch == "}":
                seg_start = i + 1
                i += 1
            else:
                i += 1

    out: list[tuple[str, str]] = []
    scan(css, "", out)
    return out


class TestMinifiedAssetsServed:
    def test_bases_reference_minified_css_and_js(self):
        for base in BASES:
            text = (TEMPLATES_DIR / base).read_text(encoding="utf-8")
            assert "quick-website.min.css" in text, f"{base} does not use quick-website.min.css"
            assert "asset('css/quick-website.css')" not in text
            assert "asset('js/quick-website.js')" not in text
        for base in BASES[:4]:
            text = (TEMPLATES_DIR / base).read_text(encoding="utf-8")
            assert "quick-website.min.js" in text, f"{base} does not use quick-website.min.js"

    def test_min_css_is_not_a_stale_build(self):
        css = CSS_MIN.read_text(encoding="utf-8")
        assert _rule_count(css) >= MIN_RULE_FLOOR, (
            f"quick-website.min.css has only {_rule_count(css)} rules; "
            "it looks like a stale/truncated build. Regenerate with `npm run build`."
        )

    def test_min_css_smaller_than_source(self):
        assert CSS_MIN.stat().st_size < CSS_SOURCE.stat().st_size

    def test_min_js_is_non_trivial(self):
        assert JS_MIN.exists()
        assert JS_MIN.stat().st_size > 5000, "quick-website.min.js looks truncated"

    def test_asset_references_resolve(self):
        missing = []
        for base in BASES:
            text = (TEMPLATES_DIR / base).read_text(encoding="utf-8")
            for m in re.finditer(r"asset\('([^']+)'\)", text):
                rel = STATIC_DIR / "assets" / m.group(1)
                if not rel.is_file():
                    missing.append(f"{base}: asset('{m.group(1)}')")
            for m in re.finditer(r"filename='(/assets/[^']+)'", text):
                rel = STATIC_DIR / m.group(1).lstrip("/")
                if not rel.is_file():
                    missing.append(f"{base}: {m.group(1)}")
        assert not missing, f"bases reference missing assets: {missing}"


class TestPagesServeMinifiedAssets:
    def test_homepage_uses_minified_css_and_js(self, seeded_client):
        body = seeded_client.get("/").get_data(as_text=True)
        assert "quick-website.min.css" in body
        assert "quick-website.min.js" in body
        assert "asset('css/quick-website.css')" not in body
        assert "asset('js/quick-website.js')" not in body

    def test_light_base_page_uses_minified_assets(self, seeded_client):
        body = seeded_client.get("/news/").get_data(as_text=True)
        assert "quick-website.min.css" in body
        assert "quick-website.min.js" in body
        assert "asset('css/quick-website.css')" not in body


class TestPurgeCompleteness:
    def test_every_template_class_that_had_a_rule_survives(self):
        source = CSS_SOURCE.read_text(encoding="utf-8")
        minified = CSS_MIN.read_text(encoding="utf-8")
        source_classes = _class_tokens(source)
        min_classes = _class_tokens(minified)

        template_classes = set()
        for p in TEMPLATES_DIR.rglob("*.html"):
            text = p.read_text(encoding="utf-8")
            # Skip inline JS/CSS blocks (their `class="..."` strings are not
            # HTML class attributes) and Jinja expressions.
            text = re.sub(r"<script\b.*?</script>", " ", text, flags=re.S)
            text = re.sub(r"<style\b.*?</style>", " ", text, flags=re.S)
            text = re.sub(r"\{\{.*?\}\}|\{%.*?%\}", " ", text, flags=re.S)
            for m in re.finditer(r'class\s*=\s*"([^"]*)"', text):
                template_classes |= _class_tokens(m.group(1))

        def is_dynamic(c: str) -> bool:
            return any(c.startswith(p) for p in DYNAMIC_PREFIXES)

        # Classes purgecss treats as "used": template classes plus any class in
        # a dynamic (greedy-safelisted) family.
        used_classes = template_classes & source_classes
        effective_used = used_classes | {c for c in source_classes if is_dynamic(c)}

        purged = used_classes - min_classes
        if not purged:
            return

        # purgecss keeps a selector iff EVERY class in it is used. A purged
        # class is legitimate iff every source selector referencing it also
        # references some companion class that is itself unused.
        rules = _leaf_rules(source)
        unexplained = []
        for cls in sorted(purged):
            pattern = re.compile(r"(?<![\w-])" + re.escape(cls) + r"(?![\w-])")
            referencing = [sel for sel, _ in rules if pattern.search(sel)]
            fully_explained = True
            for sel in referencing:
                companions = (_class_tokens(sel) & source_classes) - {cls}
                if companions <= effective_used:
                    fully_explained = False
                    break
            if not fully_explained:
                unexplained.append((cls, referencing))
        assert not unexplained, (
            "classes used in templates were removed by the purge without a "
            "justifying unused companion class: "
            f"{[c for c, _ in unexplained]}. Regenerate with `npm run build` and "
            "check the purge safelist in scripts/build-assets.mjs."
        )
