name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - run: pip install ruff mdformat pytest

      - run: ruff format --check src/
      - run: ruff check src/
      - run: mdformat --check .
      - run: pytest
